MCU = atmega32u4
BOOTLOADER = caterina

# Vial / VIA 有効化
VIA_ENABLE = yes
VIAL_ENABLE = yes

# リンク時最適化（容量削減）
LTO_ENABLE = yes

# ATmega32U4 のメモリ節約およびリンクエラー解消
QMK_SETTINGS = no

# 未使用機能の無効化
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
AUDIO_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no
LAYER_LOCK_ENABLE = no
LEADER_KEY_ENABLE = no