# Bootmagic（Escキー長押しでUSB接続するとブートローダー起動）
BOOTMAGIC_ENABLE = yes

# トラックポイント（PS/2、CLK=D1/INT1, DATA=D0）
PS2_MOUSE_ENABLE = yes
PS2_ENABLE = yes
PS2_DRIVER = interrupt

# マウスボタン（KC_BTN1〜3）をキーに割り当てるため
MOUSEKEY_ENABLE = yes

# Vial / VIA 有効化
VIA_ENABLE = yes
VIAL_ENABLE = yes

# リンク時最適化（容量削減）
LTO_ENABLE = yes

# メモリ節約（32KB制限対策）
QMK_SETTINGS = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
AUDIO_ENABLE = no
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
AUTO_SHIFT_ENABLE = no
CAPS_WORD_ENABLE = no
KEY_OVERRIDE_ENABLE = no
REPEAT_KEY_ENABLE = no
LAYER_LOCK_ENABLE = no
LEADER_KEY_ENABLE = no
