name: Build Vial Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/qmk/qmk_cli:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build firmware
      run: |
        qmk compile -kb "DO52 YK" -km vial

    - name: Upload HEX Artifact
      uses: actions/upload-artifact@v4
      with:
        name: do52_vial_hex
        path: .build/*.hex
