name: Build Vial Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    container: ghcr.io/vial-kb/vial:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Safe directory config
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Build firmware
      run: |
        make do52:vial

    - name: Upload HEX Artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: do52_vial_hex
        path: |
          *.hex
          .build/*.hex